from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class GlossaryEntry:
    term_id: str
    term: str
    aliases: list[str]
    category: str
    definition: str
    related_tables: list[str]
    related_columns: list[str]
    value_examples: list[str]


GLOSSARY_ENTRIES: list[GlossaryEntry] = [
    GlossaryEntry(
        term_id="table.competitions",
        term="competitions",
        aliases=["leagues", "tournaments", "competition seasons"],
        category="table",
        definition="Competition seasons available for querying, with country, season, gender, and youth or international flags.",
        related_tables=["competitions"],
        related_columns=[
            "competitions.competition_id",
            "competitions.name",
            "competitions.season_name",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.teams",
        term="teams",
        aliases=["clubs", "national teams", "sides"],
        category="table",
        definition="Teams that appear in matches, independent of the upstream data source.",
        related_tables=["teams"],
        related_columns=["teams.team_id", "teams.name", "teams.country"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.players",
        term="players",
        aliases=["footballers", "squad members"],
        category="table",
        definition="Players who appear in lineups or match events.",
        related_tables=["players"],
        related_columns=["players.player_id", "players.name", "players.country"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.player_teams",
        term="player teams",
        aliases=["rosters", "squad links", "player team memberships"],
        category="table",
        definition="Relationship between players and teams, including team-specific shirt number and positions.",
        related_tables=["player_teams", "players", "teams"],
        related_columns=[
            "player_teams.player_id",
            "player_teams.team_id",
            "player_teams.positions",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.matches",
        term="matches",
        aliases=["games", "fixtures"],
        category="table",
        definition="Football matches with competition, date, teams, score, stage, venue, and referee context.",
        related_tables=["matches"],
        related_columns=[
            "matches.match_id",
            "matches.competition_id",
            "matches.match_date",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.match_events",
        term="match events",
        aliases=["event data", "on-ball events", "event log"],
        category="table",
        definition="Chronological neutral match events with time, team, player, location, type, outcome, and enriched football attributes.",
        related_tables=["match_events"],
        related_columns=[
            "match_events.event_id",
            "match_events.match_id",
            "match_events.type",
        ],
        value_examples=["Shot", "Pass", "Carry"],
    ),
    GlossaryEntry(
        term_id="table.spadl_actions",
        term="SPADL actions",
        aliases=["converted actions", "analytics actions"],
        category="table",
        definition="Neutral events converted to SPADL actions with normalized left to right coordinates and action labels.",
        related_tables=["spadl_actions", "match_events"],
        related_columns=[
            "spadl_actions.action_id",
            "spadl_actions.source_event_id",
            "spadl_actions.spadl_type",
        ],
        value_examples=["pass", "shot", "dribble"],
    ),
    GlossaryEntry(
        term_id="table.action_values",
        term="action values",
        aliases=["action ratings", "xT and VAEP"],
        category="table",
        definition="Per-action analytics values including expected threat and VAEP components.",
        related_tables=["action_values", "spadl_actions"],
        related_columns=[
            "action_values.action_id",
            "action_values.xt_value",
            "action_values.vaep_value",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.shot_xg",
        term="shot xG",
        aliases=["expected goals table", "shot expected goals"],
        category="table",
        definition="Open expected goals values for shot actions, keyed to the SPADL action.",
        related_tables=["shot_xg", "spadl_actions"],
        related_columns=["shot_xg.action_id", "shot_xg.match_id", "shot_xg.xg"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.glossary_terms",
        term="glossary terms",
        aliases=["retrieval glossary", "grounding terms"],
        category="table",
        definition="Curated retrieval entries that map football language to neutral schema objects and exact stored values.",
        related_tables=["glossary_terms"],
        related_columns=[
            "glossary_terms.term",
            "glossary_terms.related_columns",
            "glossary_terms.value_examples",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.competition_id",
        term="competition id",
        aliases=["competition season id", "tournament id"],
        category="column",
        definition="Stable neutral identifier for a competition season. Join matches to competitions through this id.",
        related_tables=["competitions", "matches"],
        related_columns=["competitions.competition_id", "matches.competition_id"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.season",
        term="season",
        aliases=["season name", "year"],
        category="column",
        definition="Season label stored on competitions and copied onto matches for convenient filtering.",
        related_tables=["competitions", "matches"],
        related_columns=["competitions.season_name", "matches.season_name"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.match_date",
        term="match date",
        aliases=["game date", "fixture date"],
        category="column",
        definition="Calendar date for a match. Use matches.match_date for date filters and ordering.",
        related_tables=["matches"],
        related_columns=["matches.match_date"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.home_away_teams",
        term="home and away teams",
        aliases=["home team", "away team", "opponents"],
        category="column",
        definition="Home and away team ids on matches. Join each id to teams.team_id for names.",
        related_tables=["matches", "teams"],
        related_columns=["matches.home_team_id", "matches.away_team_id", "teams.team_id"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.score",
        term="score",
        aliases=["goals in match", "final score", "match score"],
        category="column",
        definition="Home and away score stored on matches. Use event outcomes for shot-level goals.",
        related_tables=["matches"],
        related_columns=["matches.home_score", "matches.away_score"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.player_name",
        term="player name",
        aliases=["footballer name", "player display"],
        category="column",
        definition="Player names are stored in players.name. Event rows also copy player_name for auditing.",
        related_tables=["players", "match_events"],
        related_columns=["players.name", "match_events.player_name"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.team_name",
        term="team name",
        aliases=["club name", "side name", "nation name"],
        category="column",
        definition="Team names are stored in teams.name. Event rows also copy team_name for auditing.",
        related_tables=["teams", "match_events"],
        related_columns=["teams.name", "match_events.team_name"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.event_time",
        term="event time",
        aliases=["minute", "second", "match clock"],
        category="column",
        definition="Event time is stored as period, minute, and second on match_events. SPADL actions also store time_seconds.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=[
            "match_events.period",
            "match_events.minute",
            "match_events.second",
            "spadl_actions.time_seconds",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.event_sequence",
        term="event sequence",
        aliases=["event order", "chronological order"],
        category="column",
        definition="Event order within a match is match_events.sequence. Converted action order is spadl_actions.action_order.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.sequence", "spadl_actions.action_order"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.event_team",
        term="event team",
        aliases=["acting team", "team on event"],
        category="column",
        definition="Team responsible for an event or SPADL action. Join team_id to teams.team_id for the team name.",
        related_tables=["match_events", "spadl_actions", "teams"],
        related_columns=[
            "match_events.team_id",
            "spadl_actions.team_id",
            "teams.team_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.event_player",
        term="event player",
        aliases=["acting player", "player on event"],
        category="column",
        definition="Player responsible for an event or SPADL action. Join player_id to players.player_id for the player name.",
        related_tables=["match_events", "spadl_actions", "players"],
        related_columns=[
            "match_events.player_id",
            "spadl_actions.player_id",
            "players.player_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.possession_team",
        term="possession team",
        aliases=["team in possession", "possessing team"],
        category="column",
        definition="Team considered in possession at the time of a neutral event.",
        related_tables=["match_events", "teams"],
        related_columns=[
            "match_events.possession_team_id",
            "match_events.possession_team_name",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.start_location",
        term="start location",
        aliases=["event location", "start coordinates", "where it began"],
        category="column",
        definition="Neutral event start coordinates use match_events.location_x and location_y. SPADL uses start_x and start_y.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=[
            "match_events.location_x",
            "match_events.location_y",
            "spadl_actions.start_x",
            "spadl_actions.start_y",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.end_location",
        term="end location",
        aliases=["end coordinates", "where it ended", "destination"],
        category="column",
        definition="Neutral event end coordinates use match_events.end_location_x and end_location_y. SPADL uses end_x and end_y.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=[
            "match_events.end_location_x",
            "match_events.end_location_y",
            "spadl_actions.end_x",
            "spadl_actions.end_y",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.body_part",
        term="body part",
        aliases=["foot", "head", "left foot", "right foot"],
        category="column",
        definition="Neutral body part on match_events and SPADL body part on spadl_actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.body_part", "spadl_actions.spadl_bodypart"],
        value_examples=[
            "left_foot",
            "right_foot",
            "head",
            "other",
            "keeper_hands",
            "foot_left",
            "foot_right",
        ],
    ),
    GlossaryEntry(
        term_id="column.under_pressure",
        term="under pressure",
        aliases=["pressured", "while pressed", "opponent pressure"],
        category="concept",
        definition="Boolean flag on match_events showing whether the event happened while the player was under opponent pressure.",
        related_tables=["match_events"],
        related_columns=["match_events.under_pressure"],
        value_examples=["true", "false"],
    ),
    GlossaryEntry(
        term_id="column.play_pattern",
        term="play pattern",
        aliases=["phase of play", "restart source"],
        category="column",
        definition="Neutral play pattern for a match event, such as regular play, counter, or a restart source.",
        related_tables=["match_events"],
        related_columns=["match_events.play_pattern"],
        value_examples=[
            "regular_play",
            "from_corner",
            "from_free_kick",
            "from_throw_in",
            "from_goal_kick",
            "from_kick_off",
            "from_counter",
            "from_keeper",
            "other",
        ],
    ),
    GlossaryEntry(
        term_id="column.pass_type",
        term="pass type",
        aliases=["kind of pass", "restart pass"],
        category="column",
        definition="Neutral pass type for pass events, useful for set pieces and restarts.",
        related_tables=["match_events"],
        related_columns=["match_events.pass_type"],
        value_examples=[
            "open_play",
            "corner",
            "free_kick",
            "throw_in",
            "goal_kick",
            "kick_off",
        ],
    ),
    GlossaryEntry(
        term_id="column.shot_type",
        term="shot type",
        aliases=["kind of shot", "penalty shot", "free kick shot"],
        category="column",
        definition="Neutral shot type for shot events.",
        related_tables=["match_events"],
        related_columns=["match_events.shot_type"],
        value_examples=["open_play", "penalty", "free_kick", "corner"],
    ),
    GlossaryEntry(
        term_id="column.spadl_type",
        term="SPADL action type",
        aliases=["action type", "analytics action label"],
        category="column",
        definition="Lowercase SPADL action label stored on spadl_actions.spadl_type.",
        related_tables=["spadl_actions"],
        related_columns=["spadl_actions.spadl_type"],
        value_examples=[
            "pass",
            "cross",
            "throw_in",
            "freekick_crossed",
            "freekick_short",
            "corner_crossed",
            "corner_short",
            "take_on",
            "foul",
            "tackle",
            "interception",
            "shot",
            "shot_penalty",
            "shot_freekick",
            "keeper_save",
            "clearance",
            "bad_touch",
            "non_action",
            "dribble",
            "goalkick",
        ],
    ),
    GlossaryEntry(
        term_id="column.spadl_result",
        term="SPADL result",
        aliases=["action result", "success or failure"],
        category="column",
        definition="Lowercase result label for a SPADL action.",
        related_tables=["spadl_actions"],
        related_columns=["spadl_actions.spadl_result"],
        value_examples=[
            "fail",
            "success",
            "offside",
            "owngoal",
            "yellow_card",
            "red_card",
        ],
    ),
    GlossaryEntry(
        term_id="metric.expected_threat",
        term="expected threat",
        aliases=["xT", "threat value", "threat added"],
        category="metric",
        definition="Expected threat value for a SPADL action. Use action_values.xt_value and join to spadl_actions by action_id.",
        related_tables=["action_values", "spadl_actions"],
        related_columns=["action_values.xt_value", "action_values.action_id"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.vaep",
        term="VAEP",
        aliases=["valuing actions", "action value", "total VAEP"],
        category="metric",
        definition="Total VAEP value for a SPADL action. Use action_values.vaep_value and join to spadl_actions by action_id.",
        related_tables=["action_values", "spadl_actions"],
        related_columns=["action_values.vaep_value", "action_values.action_id"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.vaep_offensive",
        term="offensive VAEP",
        aliases=["attacking VAEP", "offensive value"],
        category="metric",
        definition="Offensive component of VAEP, stored on action_values.vaep_offensive.",
        related_tables=["action_values"],
        related_columns=["action_values.vaep_offensive"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.vaep_defensive",
        term="defensive VAEP",
        aliases=["defending VAEP", "defensive value"],
        category="metric",
        definition="Defensive component of VAEP, stored on action_values.vaep_defensive.",
        related_tables=["action_values"],
        related_columns=["action_values.vaep_defensive"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.expected_goals",
        term="expected goals",
        aliases=["xG", "shot probability", "goal probability"],
        category="metric",
        definition="Open expected goals value per shot. Use shot_xg.xg and join to spadl_actions through action_id.",
        related_tables=["shot_xg", "spadl_actions"],
        related_columns=["shot_xg.xg", "shot_xg.action_id"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="event.shots",
        term="shots",
        aliases=["attempts", "shot attempts"],
        category="event_type",
        definition="Shot events in match_events use type Shot. Shot actions in SPADL include shot, shot_penalty, and shot_freekick.",
        related_tables=["match_events", "spadl_actions", "shot_xg"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Shot", "shot", "shot_penalty", "shot_freekick"],
    ),
    GlossaryEntry(
        term_id="event.passes",
        term="passes",
        aliases=["passing", "completed passes", "pass attempts"],
        category="event_type",
        definition="Pass events in match_events use type Pass. SPADL pass actions include pass and set-piece pass labels.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Pass", "pass", "throw_in", "freekick_short", "corner_short"],
    ),
    GlossaryEntry(
        term_id="event.crosses",
        term="crosses",
        aliases=["crossed balls", "wide deliveries"],
        category="action_type",
        definition="Crosses are pass events with match_events.is_cross true, or SPADL actions with cross-like action types.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=[
            "match_events.type",
            "match_events.is_cross",
            "spadl_actions.spadl_type",
        ],
        value_examples=["Pass", "true", "cross", "corner_crossed", "freekick_crossed"],
    ),
    GlossaryEntry(
        term_id="event.carries",
        term="carries",
        aliases=["ball carries", "progressive carries"],
        category="event_type",
        definition="Carry events in match_events use type Carry. In SPADL, carries map to dribble actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Carry", "dribble"],
    ),
    GlossaryEntry(
        term_id="event.dribbles",
        term="dribbles",
        aliases=["dribble events", "beating a defender"],
        category="event_type",
        definition="Neutral Dribble events represent attempts to beat an opponent. SPADL stores these as take_on actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Dribble", "take_on"],
    ),
    GlossaryEntry(
        term_id="event.take_ons",
        term="take ons",
        aliases=["take-ons", "one on ones"],
        category="action_type",
        definition="SPADL take_on actions correspond to neutral Dribble events.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Dribble", "take_on"],
    ),
    GlossaryEntry(
        term_id="event.tackles",
        term="tackles",
        aliases=["challenges", "defensive duels"],
        category="action_type",
        definition="Duel events can map to SPADL tackle actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Duel", "tackle"],
    ),
    GlossaryEntry(
        term_id="event.interceptions",
        term="interceptions",
        aliases=["intercepted passes", "cut outs"],
        category="event_type",
        definition="Interception events and SPADL interception actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Interception", "interception"],
    ),
    GlossaryEntry(
        term_id="event.clearances",
        term="clearances",
        aliases=["clear the ball", "defensive clearances"],
        category="event_type",
        definition="Clearance events and SPADL clearance actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Clearance", "clearance"],
    ),
    GlossaryEntry(
        term_id="event.fouls",
        term="fouls",
        aliases=["foul committed", "committed fouls"],
        category="event_type",
        definition="Foul events in match_events and SPADL foul actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Foul Committed", "Foul Won", "foul"],
    ),
    GlossaryEntry(
        term_id="event.goalkeeper_actions",
        term="goalkeeper actions",
        aliases=["keeper saves", "goalie actions"],
        category="action_type",
        definition="Goal keeper events can map to SPADL keeper actions such as keeper_save.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Goal Keeper", "keeper_save", "keeper_claim", "keeper_punch"],
    ),
    GlossaryEntry(
        term_id="event.bad_touches",
        term="bad touches",
        aliases=["miscontrols", "dispossessions", "bad control"],
        category="action_type",
        definition="Miscontrol and Dispossessed event labels map to SPADL bad_touch.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.type", "spadl_actions.spadl_type"],
        value_examples=["Miscontrol", "Dispossessed", "bad_touch"],
    ),
    GlossaryEntry(
        term_id="concept.set_pieces",
        term="set pieces",
        aliases=["restarts", "dead ball situations"],
        category="concept",
        definition="Set pieces are represented through pass_type, shot_type, play_pattern, and SPADL set-piece action labels.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=[
            "match_events.pass_type",
            "match_events.shot_type",
            "match_events.play_pattern",
            "spadl_actions.spadl_type",
        ],
        value_examples=[
            "corner",
            "free_kick",
            "throw_in",
            "goal_kick",
            "corner_crossed",
            "freekick_short",
        ],
    ),
    GlossaryEntry(
        term_id="concept.corners",
        term="corners",
        aliases=["corner kicks", "corner crosses"],
        category="concept",
        definition="Corners can be found through play_pattern, pass_type, shot_type, or SPADL corner action labels.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=[
            "match_events.play_pattern",
            "match_events.pass_type",
            "match_events.shot_type",
            "spadl_actions.spadl_type",
        ],
        value_examples=["from_corner", "corner", "corner_crossed", "corner_short"],
    ),
    GlossaryEntry(
        term_id="concept.free_kicks",
        term="free kicks",
        aliases=["free-kicks", "direct free kicks"],
        category="concept",
        definition="Free kicks can appear as pass types, shot types, play patterns, or SPADL free kick action labels.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=[
            "match_events.play_pattern",
            "match_events.pass_type",
            "match_events.shot_type",
            "spadl_actions.spadl_type",
        ],
        value_examples=[
            "from_free_kick",
            "free_kick",
            "freekick_crossed",
            "freekick_short",
            "shot_freekick",
        ],
    ),
    GlossaryEntry(
        term_id="concept.throw_ins",
        term="throw ins",
        aliases=["throw-ins", "throws"],
        category="concept",
        definition="Throw ins are pass events with pass_type throw_in or SPADL actions with spadl_type throw_in.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.pass_type", "spadl_actions.spadl_type"],
        value_examples=["throw_in"],
    ),
    GlossaryEntry(
        term_id="concept.goal_kicks",
        term="goal kicks",
        aliases=["goal-kicks", "keeper restarts"],
        category="concept",
        definition="Goal kicks are pass events with pass_type goal_kick or SPADL goalkick actions.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.pass_type", "spadl_actions.spadl_type"],
        value_examples=["goal_kick", "goalkick"],
    ),
    GlossaryEntry(
        term_id="concept.kick_offs",
        term="kick offs",
        aliases=["kickoffs", "kick-off passes"],
        category="concept",
        definition="Kick offs are pass events with pass_type kick_off or play_pattern from_kick_off.",
        related_tables=["match_events"],
        related_columns=["match_events.pass_type", "match_events.play_pattern"],
        value_examples=["kick_off", "from_kick_off"],
    ),
    GlossaryEntry(
        term_id="concept.penalties",
        term="penalties",
        aliases=["penalty kicks", "spot kicks"],
        category="concept",
        definition="Penalty shots use match_events.shot_type penalty or SPADL shot_penalty.",
        related_tables=["match_events", "spadl_actions", "shot_xg"],
        related_columns=["match_events.shot_type", "spadl_actions.spadl_type"],
        value_examples=["penalty", "shot_penalty"],
    ),
    GlossaryEntry(
        term_id="concept.goals",
        term="goals",
        aliases=["scored goals", "finishes"],
        category="concept",
        definition="Goals at event level are shot outcomes with value Goal. Successful SPADL shots have result success.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.outcome", "spadl_actions.spadl_result"],
        value_examples=["Goal", "success"],
    ),
    GlossaryEntry(
        term_id="concept.own_goals",
        term="own goals",
        aliases=["own-goals"],
        category="concept",
        definition="Own goals can be represented by SPADL result owngoal.",
        related_tables=["spadl_actions"],
        related_columns=["spadl_actions.spadl_result"],
        value_examples=["owngoal"],
    ),
    GlossaryEntry(
        term_id="concept.cards",
        term="cards",
        aliases=["yellow cards", "red cards", "bookings"],
        category="concept",
        definition="Card outcomes are represented in SPADL results when actions carry yellow or red card labels.",
        related_tables=["spadl_actions"],
        related_columns=["spadl_actions.spadl_result"],
        value_examples=["yellow_card", "red_card"],
    ),
    GlossaryEntry(
        term_id="concept.successful_actions",
        term="successful actions",
        aliases=["completed actions", "successful passes"],
        category="concept",
        definition="SPADL successful actions use spadl_result success. Neutral event outcomes keep original label casing in match_events.outcome.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.outcome", "spadl_actions.spadl_result"],
        value_examples=["Complete", "success"],
    ),
    GlossaryEntry(
        term_id="concept.failed_actions",
        term="failed actions",
        aliases=["unsuccessful actions", "incomplete passes", "missed shots"],
        category="concept",
        definition="SPADL failed actions use spadl_result fail. Neutral outcomes can include Incomplete, Saved, or other stored labels.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.outcome", "spadl_actions.spadl_result"],
        value_examples=["Incomplete", "Saved", "fail"],
    ),
    GlossaryEntry(
        term_id="concept.offside",
        term="offside",
        aliases=["offsides", "offside passes"],
        category="concept",
        definition="Offside is represented as a SPADL result and can also appear as a neutral event outcome label.",
        related_tables=["match_events", "spadl_actions"],
        related_columns=["match_events.outcome", "spadl_actions.spadl_result"],
        value_examples=["Pass Offside", "offside"],
    ),
    GlossaryEntry(
        term_id="concept.open_play",
        term="open play",
        aliases=["regular play", "not a set piece"],
        category="concept",
        definition="Open play appears as pass_type open_play, shot_type open_play, or play_pattern regular_play.",
        related_tables=["match_events"],
        related_columns=[
            "match_events.pass_type",
            "match_events.shot_type",
            "match_events.play_pattern",
        ],
        value_examples=["open_play", "regular_play"],
    ),
    GlossaryEntry(
        term_id="concept.counter_attack",
        term="counter attack",
        aliases=["counter", "transition attack"],
        category="concept",
        definition="Counter attacks use the neutral play_pattern value from_counter.",
        related_tables=["match_events"],
        related_columns=["match_events.play_pattern"],
        value_examples=["from_counter"],
    ),
    GlossaryEntry(
        term_id="concept.from_keeper",
        term="from keeper",
        aliases=["keeper distribution", "goalkeeper possession start"],
        category="concept",
        definition="Events from keeper possession use the neutral play_pattern value from_keeper.",
        related_tables=["match_events"],
        related_columns=["match_events.play_pattern"],
        value_examples=["from_keeper"],
    ),
    GlossaryEntry(
        term_id="concept.by_team",
        term="by team",
        aliases=["team totals", "group by team"],
        category="concept",
        definition="Team aggregations should group by team ids and join to teams for names.",
        related_tables=["teams", "match_events", "spadl_actions", "shot_xg"],
        related_columns=[
            "teams.team_id",
            "match_events.team_id",
            "spadl_actions.team_id",
            "shot_xg.team_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="concept.by_player",
        term="by player",
        aliases=["player totals", "leaderboard", "rank players"],
        category="concept",
        definition="Player aggregations should group by player ids and join to players for names.",
        related_tables=["players", "match_events", "spadl_actions", "shot_xg"],
        related_columns=[
            "players.player_id",
            "match_events.player_id",
            "spadl_actions.player_id",
            "shot_xg.player_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="concept.player_xt_totals",
        term="player expected threat totals",
        aliases=["player xT leaderboard", "most threat by player"],
        category="concept",
        definition="Sum action_values.xt_value after joining action_values to spadl_actions by action_id, then group by spadl_actions.player_id.",
        related_tables=["action_values", "spadl_actions", "players"],
        related_columns=[
            "action_values.xt_value",
            "action_values.action_id",
            "spadl_actions.player_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="concept.player_vaep_totals",
        term="player VAEP totals",
        aliases=["player action value leaderboard", "best players by VAEP"],
        category="concept",
        definition="Sum action_values.vaep_value after joining action_values to spadl_actions by action_id, then group by spadl_actions.player_id.",
        related_tables=["action_values", "spadl_actions", "players"],
        related_columns=[
            "action_values.vaep_value",
            "action_values.action_id",
            "spadl_actions.player_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="concept.player_xg_totals",
        term="player expected goals totals",
        aliases=["player xG leaderboard", "most xG by player"],
        category="concept",
        definition="Sum shot_xg.xg and group by shot_xg.player_id, joining to players for names.",
        related_tables=["shot_xg", "players"],
        related_columns=["shot_xg.xg", "shot_xg.player_id", "players.player_id"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.positions",
        term="positions",
        aliases=["player positions", "roles"],
        category="position",
        definition="Known positions for a player with a team are stored as text values in player_teams.positions.",
        related_tables=["player_teams", "players", "teams"],
        related_columns=["player_teams.positions"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.jersey_number",
        term="jersey number",
        aliases=["shirt number", "squad number"],
        category="column",
        definition="Player shirt number for a team is stored on player_teams.jersey_number.",
        related_tables=["player_teams"],
        related_columns=["player_teams.jersey_number"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.venue",
        term="venue",
        aliases=["stadium", "ground"],
        category="column",
        definition="Match venue name when known, stored on matches.venue.",
        related_tables=["matches"],
        related_columns=["matches.venue"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.referee",
        term="referee",
        aliases=["match official", "official"],
        category="column",
        definition="Main referee name when known, stored on matches.referee.",
        related_tables=["matches"],
        related_columns=["matches.referee"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.gender_category",
        term="competition gender",
        aliases=["men women mixed", "gender category"],
        category="column",
        definition="Gender category for competitions and teams. Values are female, male, mixed, or unknown.",
        related_tables=["competitions", "teams"],
        related_columns=["competitions.gender", "teams.gender"],
        value_examples=["female", "male", "mixed", "unknown"],
    ),
    GlossaryEntry(
        term_id="column.match_stage",
        term="match stage",
        aliases=["round", "competition stage", "phase"],
        category="column",
        definition="Competition stage for a match, such as group stage or final, stored on matches.stage.",
        related_tables=["matches"],
        related_columns=["matches.stage"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.match_week",
        term="match week",
        aliases=["round number", "fixture week"],
        category="column",
        definition="Competition round or match week number when known, stored on matches.match_week.",
        related_tables=["matches"],
        related_columns=["matches.match_week"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.international_competition",
        term="international competition",
        aliases=["national team tournament", "international flag"],
        category="column",
        definition="competitions.is_international is true when the competition is international.",
        related_tables=["competitions"],
        related_columns=["competitions.is_international"],
        value_examples=["true", "false"],
    ),
    GlossaryEntry(
        term_id="column.youth_competition",
        term="youth competition",
        aliases=["youth tournament", "under age competition"],
        category="column",
        definition="competitions.is_youth is true when the competition is a youth competition.",
        related_tables=["competitions"],
        related_columns=["competitions.is_youth"],
        value_examples=["true", "false"],
    ),
    GlossaryEntry(
        term_id="concept.shot_xg_event_join",
        term="join expected goals to shot event attributes",
        aliases=[
            "shot_xg join path",
            "xg by shot_type",
            "xg by body_part",
            "xg by play_pattern",
            "expected goals with shot filters",
        ],
        category="concept",
        definition="shot_xg has no event attributes. To filter expected goals by shot_type, body_part, or play_pattern, join shot_xg.action_id to spadl_actions.action_id, then spadl_actions.source_event_id to match_events.event_id. Never join shot_xg to match_events on match_id, which multiplies rows and inflates summed xg.",
        related_tables=["shot_xg", "spadl_actions", "match_events"],
        related_columns=[
            "shot_xg.action_id",
            "spadl_actions.action_id",
            "spadl_actions.source_event_id",
            "match_events.event_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.match_predictions",
        term="match predictions",
        aliases=[
            "win probability",
            "predictions",
            "odds",
            "forecast",
            "who will win",
            "chance of winning",
        ],
        category="table",
        definition="Pre-match win, draw, and loss probabilities for each actual match, produced by the Elo and Dixon-Coles models and stored for querying. One row per match. Probabilities are model estimates for entertainment, not betting advice.",
        related_tables=["match_predictions", "matches", "teams"],
        related_columns=[
            "match_predictions.match_id",
            "match_predictions.prob_home_win",
            "match_predictions.prob_draw",
            "match_predictions.prob_away_win",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.team_ratings",
        term="team ratings",
        aliases=["elo", "team strength", "power ranking", "strongest team"],
        category="table",
        definition="Model team strength ratings used for win probability, with one row per team. Holds the Elo rating and the Dixon-Coles attack and defense strengths.",
        related_tables=["team_ratings", "teams"],
        related_columns=[
            "team_ratings.team_id",
            "team_ratings.elo_rating",
            "team_ratings.attack_strength",
            "team_ratings.defense_strength",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.win_probability",
        term="win probability",
        aliases=[
            "chance of winning",
            "probability a team wins",
            "odds of winning",
            "win chance",
            "likelihood of winning",
        ],
        category="metric",
        definition="Pre-match probability that a team wins a specific match, from 0 to 1. Read match_predictions.prob_home_win when the team is the home team or match_predictions.prob_away_win when the team is the away team. Filter by home_team_name or away_team_name, or join the team ids to teams. These are model estimates, not betting advice.",
        related_tables=["match_predictions", "teams"],
        related_columns=[
            "match_predictions.prob_home_win",
            "match_predictions.prob_away_win",
            "match_predictions.home_team_name",
            "match_predictions.away_team_name",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.draw_probability",
        term="draw probability",
        aliases=["chance of a draw", "probability of a tie", "odds of a draw"],
        category="metric",
        definition="Pre-match probability that a specific match is level after regulation and extra time, from 0 to 1. Read match_predictions.prob_draw. Penalty shootouts are not modeled and count as draws.",
        related_tables=["match_predictions"],
        related_columns=["match_predictions.prob_draw"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.elo_rating",
        term="elo rating",
        aliases=["team strength rating", "power rating", "ranking points"],
        category="metric",
        definition="Team strength on the Elo scale after walking forward through every match. Higher means stronger. Read team_ratings.elo_rating and join team_ratings.team_id to teams.team_id for the name.",
        related_tables=["team_ratings", "teams"],
        related_columns=["team_ratings.elo_rating", "team_ratings.team_id"],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="metric.team_attack_defense_strength",
        term="attack and defense strength",
        aliases=[
            "attacking strength",
            "defensive strength",
            "scoring strength",
            "how strong a team attacks",
        ],
        category="metric",
        definition="Dixon-Coles team strengths as multipliers around 1.0. team_ratings.attack_strength above 1.0 means a team scores more than average. team_ratings.defense_strength below 1.0 means a team concedes fewer than average.",
        related_tables=["team_ratings"],
        related_columns=[
            "team_ratings.attack_strength",
            "team_ratings.defense_strength",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="concept.predicted_scoreline",
        term="predicted scoreline",
        aliases=[
            "most likely score",
            "predicted score",
            "scoreline prediction",
            "expected goals in a match",
        ],
        category="concept",
        definition="The model expected goals and single most likely exact score for a match. Read match_predictions.expected_home_goals and expected_away_goals for the means, and most_likely_home_goals and most_likely_away_goals for the single most likely scoreline.",
        related_tables=["match_predictions"],
        related_columns=[
            "match_predictions.expected_home_goals",
            "match_predictions.expected_away_goals",
            "match_predictions.most_likely_home_goals",
            "match_predictions.most_likely_away_goals",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="column.source",
        term="data source",
        aliases=["data feed", "source", "provider", "which feed", "dataset"],
        category="column",
        definition="The data feed a row came from. The source column is present on competitions, teams, players, matches, and match_events. Filter on it to restrict a query to one feed. StatsBomb rows use source statsbomb, API-Football rows use source api_football.",
        related_tables=[
            "competitions",
            "teams",
            "players",
            "matches",
            "match_events",
        ],
        related_columns=[
            "competitions.source",
            "matches.source",
            "match_events.source",
        ],
        value_examples=["statsbomb", "api_football"],
    ),
    GlossaryEntry(
        term_id="concept.feed_capabilities",
        term="feed capabilities",
        aliases=[
            "what data each feed has",
            "which competitions have expected threat",
            "which competitions have xG",
            "shot detail availability",
        ],
        category="concept",
        definition="StatsBomb competitions carry shot level event detail and the derived metrics expected threat, VAEP, and expected goals. API-Football competitions carry results, goals, cards, and squads but no shot level detail and none of those metrics. If a metric does not exist for the requested competition's feed, return no rows rather than inventing a number or borrowing from the other feed. Expected threat, VAEP, and expected goals do not exist for api_football competitions.",
        related_tables=[
            "competitions",
            "match_events",
            "action_values",
            "shot_xg",
        ],
        related_columns=[
            "competitions.source",
            "match_events.source",
            "action_values.xt_value",
            "shot_xg.xg",
        ],
        value_examples=["statsbomb", "api_football"],
    ),
    GlossaryEntry(
        term_id="table.player_metric_totals",
        term="player metric totals",
        aliases=[
            "player leaderboard",
            "player totals",
            "top players by expected threat",
            "top players by VAEP",
            "top players by expected goals",
            "best players",
        ],
        category="table",
        definition="Precomputed per player totals of expected threat, VAEP, and expected goals for one competition. Prefer this small table for a player total or leaderboard instead of summing the full action set, which is slow. Filter by competition_id or source, order by total_xt, total_vaep, or total_xg, and read player_name. Only statsbomb competitions have rows here.",
        related_tables=["player_metric_totals", "players", "competitions"],
        related_columns=[
            "player_metric_totals.player_name",
            "player_metric_totals.total_xt",
            "player_metric_totals.total_vaep",
            "player_metric_totals.total_xg",
            "player_metric_totals.competition_id",
        ],
        value_examples=[],
    ),
    GlossaryEntry(
        term_id="table.team_metric_totals",
        term="team metric totals",
        aliases=[
            "team leaderboard",
            "team totals",
            "top teams by expected threat",
            "top teams by expected goals",
            "best teams by metric",
        ],
        category="table",
        definition="Precomputed per team totals of expected threat, VAEP, and expected goals for one competition. Prefer this small table for a team total or leaderboard instead of summing the full action set. Filter by competition_id or source, order by total_xt, total_vaep, or total_xg, and read team_name. Only statsbomb competitions have rows here.",
        related_tables=["team_metric_totals", "teams", "competitions"],
        related_columns=[
            "team_metric_totals.team_name",
            "team_metric_totals.total_xt",
            "team_metric_totals.total_vaep",
            "team_metric_totals.total_xg",
            "team_metric_totals.competition_id",
        ],
        value_examples=[],
    ),
]
